version: '3'

services:
  two-factor:
    build: .
    image: claascode/twofactor
    ports:
      - "2244:2244"
    volumes:
      - /root/TwoFactor:/app
    environment:
      - GO_ENV=development
