version: '3'

services:
  two-factor:
    image: claascode/twofactor
    ports:
      - "2244:2244"
    volumes:
      - /DATA/AppData/two-factor:/app
    environment:
      - GO_ENV=development
